### ISSUE TITLE
Elasticsearch mapping corrupt if using custom products

### ISSUE THREAD

**Issue by htuscher** [shopware/platform#2727]
### PHP Version

8.0.21

### Shopware Version

6.4.15.1

### Expected behaviour

Elasticsearch should work

### Actual behaviour

```
Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [cheapestPrice.from.net] in order to sort on","index_uuid":"E6o9WUPxRWqPzHHneeAl6w","index":"ep_product_2fbb5fe2e29a4d70aa5854ce7ce3e20b_1664907324"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"ep_product_2fbb5fe2e29a4d70aa5854ce7ce3e20b_1664907324","node":"MmlmuAFsS2-ZR98ba1So2A","reason":{"type":"query_shard_exception","reason":"No mapping found for [cheapestPrice.from.net] in order to sort on","index_uuid":"E6o9WUPxRWqPzHHneeAl6w","index":"ep_product_2fbb5fe2e29a4d70aa5854ce7ce3e20b_1664907324"}}]},"status":400}
#85 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(693): Elasticsearch\Connections\Connection::process4xxError
#84 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection::Elasticsearch\Connections\{closure}
#83 /vendor/react/promise/src/FulfilledPromise.php(28): React\Promise\FulfilledPromise::then
#82 /vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): GuzzleHttp\Ring\Future\CompletedFutureValue::then
#81 /vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Core::proxy
#80 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(345): Elasticsearch\Connections\Connection::Elasticsearch\Connections\{closure}
#79 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Connections\Connection::performRequest
#78 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Transport::performRequest
#77 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1929): Elasticsearch\Client::performRequest
#76 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1353): Elasticsearch\Client::search
#75 /var/cache/prod_h4c43b43e5bee16941058fcf1c6a12a5b/ContainerJpwjRlw/proxy-classes.php(182): ContainerJpwjRlw\Client_dba3ed3::search
#74 /vendor/shopware/elasticsearch/Framework/DataAbstractionLayer/ElasticsearchEntitySearcher.php(84): Shopware\Elasticsearch\Framework\DataAbstractionLayer\ElasticsearchEntitySearcher::search
#73 /vendor/shopware/core/System/SalesChannel/Entity/SalesChannelRepository.php(214): Shopware\Core\System\SalesChannel\Entity\SalesChannelRepository::doSearch
#72 /vendor/shopware/core/System/SalesChannel/Entity/SalesChannelRepository.php(120): Shopware\Core\System\SalesChannel\Entity\SalesChannelRepository::search
#71 /vendor/store.shopware.com/swagcustomizedproducts/src/Core/Content/Product/SalesChannel/SalesChannelProductRepositoryDecorator.php(34): Swag\CustomizedProducts\Core\Content\Product\SalesChannel\SalesChannelProductRepositoryDecorator::search
#70 /vendor/store.shopware.com/acrispromotioncs/src/Component/VariantService.php(39): Acris\Promotion\Component\VariantService::loadFirstVariantIdOrderedByPrice
#69 /vendor/store.shopware.com/acrispromotioncs/src/Subscriber/ProductLoadedSubscriber.php(121): Acris\Promotion\Subscriber\ProductLoadedSubscriber::loaded
#68 /vendor/symfony/event-dispatcher/EventDispatcher.php(270): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#67 /vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#66 /vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#65 /vendor/shopware/core/Content/Flow/Dispatching/FlowDispatcher.php(51): Shopware\Core\Content\Flow\Dispatching\FlowDispatcher::dispatch
#64 /vendor/shopware/core/Framework/Webhook/WebhookDispatcher.php(96): Shopware\Core\Framework\Webhook\WebhookDispatcher::dispatch
#63 /vendor/shopware/core/Framework/Event/BusinessEventDispatcher.php(53): Shopware\Core\Framework\Event\BusinessEventDispatcher::dispatch
#62 /vendor/shopware/core/Framework/Event/NestedEventDispatcher.php(35): Shopware\Core\Framework\Event\NestedEventDispatcher::dispatch
#61 /vendor/shopware/core/Framework/Event/NestedEventDispatcher.php(31): Shopware\Core\Framework\Event\NestedEventDispatcher::dispatch
#60 /vendor/shopware/core/System/SalesChannel/Entity/SalesChannelRepository.php(206): Shopware\Core\System\SalesChannel\Entity\SalesChannelRepository::read
#59 /vendor/shopware/core/System/SalesChannel/Entity/SalesChannelRepository.php(131): Shopware\Core\System\SalesChannel\Entity\SalesChannelRepository::search
#58 /vendor/store.shopware.com/swagcustomizedproducts/src/Core/Content/Product/SalesChannel/SalesChannelProductRepositoryDecorator.php(34): Swag\CustomizedProducts\Core\Content\Product\SalesChannel\SalesChannelProductRepositoryDecorator::search
#57 /vendor/shopware/core/Content/Product/SalesChannel/Listing/ProductListingLoader.php(96): Shopware\Core\Content\Product\SalesChannel\Listing\ProductListingLoader::load
#56 /vendor/shopware/core/Content/Product/SalesChannel/Listing/ProductListingRoute.php(88): Shopware\Core\Content\Product\SalesChannel\Listing\ProductListingRoute::load
#55 /vendor/shopware/core/Content/Product/SalesChannel/Listing/CachedProductListingRoute.php(85): Shopware\Core\Content\Product\SalesChannel\Listing\CachedProductListingRoute::Shopware\Core\Content\Product\SalesChannel\Listing\{closure}
#54 /vendor/shopware/core/System/SystemConfig/SystemConfigService.php(331): Shopware\Core\System\SystemConfig\SystemConfigService::trace
#53 /vendor/shopware/core/Framework/Adapter/Cache/CacheTracer.php(42): Shopware\Core\Framework\Adapter\Cache\CacheTracer::Shopware\Core\Framework\Adapter\Cache\{closure}
#52 /vendor/shopware/core/Framework/Adapter/Translation/Translator.php(102): Shopware\Core\Framework\Adapter\Translation\Translator::trace
#51 /vendor/shopware/core/Framework/Adapter/Cache/CacheTracer.php(43): Shopware\Core\Framework\Adapter\Cache\CacheTracer::Shopware\Core\Framework\Adapter\Cache\{closure}
#50 /vendor/shopware/core/Framework/Adapter/Cache/CacheTagCollection.php(43): Shopware\Core\Framework\Adapter\Cache\CacheTagCollection::trace
#49 /vendor/shopware/core/Framework/Adapter/Cache/CacheTracer.php(44): Shopware\Core\Framework\Adapter\Cache\CacheTracer::trace
#48 /vendor/shopware/storefront/Framework/Cache/CacheTracer.php(39): Shopware\Storefront\Framework\Cache\CacheTracer::Shopware\Storefront\Framework\Cache\{closure}
#47 /vendor/shopware/storefront/Theme/ThemeConfigValueAccessor.php(57): Shopware\Storefront\Theme\ThemeConfigValueAccessor::trace
#46 /vendor/shopware/storefront/Framework/Cache/CacheTracer.php(40): Shopware\Storefront\Framework\Cache\CacheTracer::trace
#45 /vendor/shopware/core/Content/Product/SalesChannel/Listing/CachedProductListingRoute.php(86): Shopware\Core\Content\Product\SalesChannel\Listing\CachedProductListingRoute::Shopware\Core\Content\Product\SalesChannel\Listing\{closure}
#44 /vendor/symfony/cache-contracts/CacheTrait.php(72): Shopware\Core\Framework\Adapter\Cache\CacheDecorator::doGet
#43 /vendor/symfony/cache-contracts/CacheTrait.php(35): Shopware\Core\Framework\Adapter\Cache\CacheDecorator::get
#42 /vendor/shopware/core/Content/Product/SalesChannel/Listing/CachedProductListingRoute.php(91): Shopware\Core\Content\Product\SalesChannel\Listing\CachedProductListingRoute::load
#41 /vendor/shopware/core/Content/Product/SalesChannel/Listing/ResolveCriteriaProductListingRoute.php(49): Shopware\Core\Content\Product\SalesChannel\Listing\ResolveCriteriaProductListingRoute::load
#40 /vendor/store.shopware.com/moorlfoundation/src/Core/Content/Product/SalesChannel/Listing/FoundationProductListingRoute.php(49): MoorlFoundation\Core\Content\Product\SalesChannel\Listing\FoundationProductListingRoute::load
#39 /vendor/shopware/core/Content/Product/Cms/ProductListingCmsElementResolver.php(60): Shopware\Core\Content\Product\Cms\ProductListingCmsElementResolver::enrich
#38 /vendor/shopware/core/Content/Cms/DataResolver/CmsSlotsDataResolver.php(97): Shopware\Core\Content\Cms\DataResolver\CmsSlotsDataResolver::resolve
#37 /vendor/shopware/core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php(102): Shopware\Core\Content\Cms\SalesChannel\SalesChannelCmsPageLoader::loadSlotData
#36 /vendor/shopware/core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php(92): Shopware\Core\Content\Cms\SalesChannel\SalesChannelCmsPageLoader::load
#35 /vendor/store.shopware.com/swagcmsextensions/src/Service/Content/Cms/SalesChannel/SalesChannelCmsPageLoaderQuickviewDecorator.php(43): Swag\CmsExtensions\Service\Content\Cms\SalesChannel\SalesChannelCmsPageLoaderQuickviewDecorator::load
#34 /vendor/store.shopware.com/swagcmsextensions/src/Service/Content/Cms/SalesChannel/SalesChannelCmsPageLoaderScrollNavigationDecorator.php(45): Swag\CmsExtensions\Service\Content\Cms\SalesChannel\SalesChannelCmsPageLoaderScrollNavigationDecorator::load
#33 /vendor/store.shopware.com/swagcmsextensions/src/Service/Content/Cms/SalesChannel/SalesChannelCmsPageLoaderBlockRuleDecorator.php(48): Swag\CmsExtensions\Service\Content\Cms\SalesChannel\SalesChannelCmsPageLoaderBlockRuleDecorator::load
#32 /vendor/store.shopware.com/netzppowerpack6/src/Core/Cms/SalesChannelCmsPageLoaderDecorator.php(28): NetzpPowerPack6\Core\Cms\SalesChannelCmsPageLoaderDecorator::load
#31 /vendor/shopware/core/Content/Category/SalesChannel/CategoryRoute.php(100): Shopware\Core\Content\Category\SalesChannel\CategoryRoute::load
#30 /vendor/store.shopware.com/swagdynamicaccess/src/Core/Content/Category/SalesChannel/DecoratedCategoryRoute.php(88): Swag\DynamicAccess\Core\Content\Category\SalesChannel\DecoratedCategoryRoute::load
#29 /vendor/shopware/core/Content/Category/SalesChannel/CachedCategoryRoute.php(92): Shopware\Core\Content\Category\SalesChannel\CachedCategoryRoute::Shopware\Core\Content\Category\SalesChannel\{closure}
#28 /vendor/shopware/core/System/SystemConfig/SystemConfigService.php(331): Shopware\Core\System\SystemConfig\SystemConfigService::trace
#27 /vendor/shopware/core/Framework/Adapter/Cache/CacheTracer.php(42): Shopware\Core\Framework\Adapter\Cache\CacheTracer::Shopware\Core\Framework\Adapter\Cache\{closure}
#26 /vendor/shopware/core/Framework/Adapter/Translation/Translator.php(102): Shopware\Core\Framework\Adapter\Translation\Translator::trace
#25 /vendor/shopware/core/Framework/Adapter/Cache/CacheTracer.php(43): Shopware\Core\Framework\Adapter\Cache\CacheTracer::Shopware\Core\Framework\Adapter\Cache\{closure}
#24 /vendor/shopware/core/Framework/Adapter/Cache/CacheTagCollection.php(43): Shopware\Core\Framework\Adapter\Cache\CacheTagCollection::trace
#23 /vendor/shopware/core/Framework/Adapter/Cache/CacheTracer.php(44): Shopware\Core\Framework\Adapter\Cache\CacheTracer::trace
#22 /vendor/shopware/storefront/Framework/Cache/CacheTracer.php(39): Shopware\Storefront\Framework\Cache\CacheTracer::Shopware\Storefront\Framework\Cache\{closure}
#21 /vendor/shopware/storefront/Theme/ThemeConfigValueAccessor.php(57): Shopware\Storefront\Theme\ThemeConfigValueAccessor::trace
#20 /vendor/shopware/storefront/Framework/Cache/CacheTracer.php(40): Shopware\Storefront\Framework\Cache\CacheTracer::trace
#19 /vendor/shopware/core/Content/Category/SalesChannel/CachedCategoryRoute.php(93): Shopware\Core\Content\Category\SalesChannel\CachedCategoryRoute::Shopware\Core\Content\Category\SalesChannel\{closure}
#18 /vendor/symfony/cache-contracts/CacheTrait.php(72): Shopware\Core\Framework\Adapter\Cache\CacheDecorator::doGet
#17 /vendor/symfony/cache-contracts/CacheTrait.php(35): Shopware\Core\Framework\Adapter\Cache\CacheDecorator::get
#16 /vendor/shopware/core/Content/Category/SalesChannel/CachedCategoryRoute.php(98): Shopware\Core\Content\Category\SalesChannel\CachedCategoryRoute::Shopware\Core\Content\Category\SalesChannel\{closure}
#15 /vendor/shopware/core/Profiling/Profiler.php(57): Shopware\Core\Profiling\Profiler::trace
#14 /vendor/shopware/core/Content/Category/SalesChannel/CachedCategoryRoute.php(101): Shopware\Core\Content\Category\SalesChannel\CachedCategoryRoute::load
#13 /vendor/store.shopware.com/swagpaypal/src/Checkout/ExpressCheckout/SalesChannel/ExpressCategoryRoute.php(93): Swag\PayPal\Checkout\ExpressCheckout\SalesChannel\ExpressCategoryRoute::load
#12 /vendor/shopware/storefront/Page/Navigation/NavigationPageLoader.php(64): Shopware\Storefront\Page\Navigation\NavigationPageLoader::load
#11 /vendor/shopware/storefront/Controller/NavigationController.php(60): Shopware\Storefront\Controller\NavigationController::index
#10 /vendor/symfony/http-kernel/HttpKernel.php(153): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#9 /vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel::handle
#8 /vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#7 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(86): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle
#6 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\Component\HttpKernel\HttpCache\HttpCache::forward
#5 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(452): Symfony\Component\HttpKernel\HttpCache\HttpCache::fetch
#4 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(346): Symfony\Component\HttpKernel\HttpCache\HttpCache::lookup
#3 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(224): Symfony\Component\HttpKernel\HttpCache\HttpCache::handle
#2 /vendor/shopware/core/HttpKernel.php(149): Shopware\Core\HttpKernel::doHandle
#1 /vendor/shopware/core/HttpKernel.php(75): Shopware\Core\HttpKernel::handle
#0 /public/index.php(78): null
```

### How to reproduce

Try to sort a listing after cheapest price if you have a custom product.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
