### ISSUE TITLE
services_test.xml in shopware/core refers to class  TestAppServer, which is not included in shopware/core

### ISSUE THREAD

**Issue by johanv** [shopware/platform#3018]
### PHP Version

8.1

### Shopware Version

6.5.0.0-rc1

### Expected behaviour

I am trying to use phpunit to run an integration test [as described in the documentation](https://developer.shopware.com/docs/guides/plugins/plugins/testing/php-unit). In the project I'm working on, we use shopware/core.

To make sure that my test finds my services, I do

```bash
./bin/console cache:clear --env=test
```

I expect a message like this:

```
[OK] Cache for the "test" environment (debug=true) was successfully cleared. 
```

### Actual behaviour

Instead, I get this error:

```
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#76
  #message: """
    Attempted to load class "TestAppServer" from namespace "Shopware\Tests\Integration\Core\Framework\App".\n
    Did you forget a "use" statement for another namespace?
    """
  #code: 0
  #file: "./var/cache/test_hb7246092d121033d0004b5977618f056/ContainerDzgKNpi/Shopware_Core_KernelTestDebugContainer.php"
  #line: 11192
  trace: {
    ./var/cache/test_hb7246092d121033d0004b5977618f056/ContainerDzgKNpi/Shopware_Core_KernelTestDebugContainer.php:11192 {
      ContainerDzgKNpi\Shopware_Core_KernelTestDebugContainer->getTestAppServerService()^
      › {
      ›     return $this->services['Shopware\\Tests\\Integration\\Core\\Framework\\App\\TestAppServer'] = new \Shopware\Tests\Integration\Core\Framework\App\TestAppServer(($this->services['GuzzleHttp\\Handler\\MockHandler'] ??= new \GuzzleHttp\Handler\MockHandler([])));
      › }
    }
    ./var/cache/test_hb7246092d121033d0004b5977618f056/ContainerDzgKNpi/Shopware_Core_KernelTestDebugContainer.php:19357 { …}
    ./var/cache/test_hb7246092d121033d0004b5977618f056/ContainerDzgKNpi/Shopware_Core_KernelTestDebugContainer.php:39387 { …}
    ./var/cache/test_hb7246092d121033d0004b5977618f056/ContainerDzgKNpi/Shopware_Core_KernelTestDebugContainer.php:37396 { …}
    ./var/cache/test_hb7246092d121033d0004b5977618f056/ContainerDzgKNpi/Shopware_Core_KernelTestDebugContainer.php:12532 { …}
    ./vendor/symfony/dependency-injection/Container.php:218 { …}
    ./vendor/symfony/dependency-injection/Container.php:198 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:75 { …}
    ./vendor/symfony/console/Application.php:168 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
    ./vendor/autoload_runtime.php:29 { …}
    ./bin/console:17 { …}
  }
}
```

It seems that the container tries to load a service TestAppServer. I guest this is because it is included in [this services_test.xml file](https://github.com/shopware/core/blob/trunk/Framework/DependencyInjection/services_test.xml#L164). But the file TestAppServer itself is not included in shopware/core. (It does exist in [the shopware/platform](https://github.com/shopware/platform/blob/trunk/tests/integration/php/Core/Framework/App/TestAppServer.php) repository.)

So I assume that either this class is missing in shopware/core, either the service definition in services_test.xml is incorrect?

### How to reproduce

Our shopware project was created with flex:

```bash
composer create-project shopware/production:dev-flex myProject
```

This installs shopware/core v6.4. The `TestAppServer` class exists in vendor/shopware/core/Framework/Test/App/TestAppServer.php.

Write a passing phpunit test. Run it. Clear the cache with --env=test. All works fine.

Now update to shopware 6.5 rc1. E.g. like this:

```php
composer remove shopware/elasticsearch  # it didn't work all at once
composer require -W shopware/administration:6.5.0.0-rc1 shopware/core:6.5.0.0-rc1 shopware/storefront:6.5.0.0-rc1
composer require shopware/elasticsearch:6.5.0.0-rc1
```

The `TestAppServer.php` file is gone now.

Run the test again:

```php
PHPUnit 10.0.16 by Sebastian Bergmann and contributors.

Error in bootstrap script: Error:
Class "Shopware\Tests\Integration\Core\Framework\App\TestAppServer" not found
#0 /home/johanvervloet/Projects/shopware-test/myProject/var/cache/test_hed5335dd30ecd5f1c764e9b26a696b68/ContainerHjoQXzC/Shopware_Core_KernelTestDebugContainer.php(20078): ContainerHjoQXzC\Shopware_Core_KernelTestDebugContainer->getTestAppServerService()
#1 /home/johanvervloet/Projects/shopware-test/myProject/var/cache/test_hed5335dd30ecd5f1c764e9b26a696b68/ContainerHjoQXzC/Shopware_Core_KernelTestDebugContainer.php(40481): ContainerHjoQXzC\Shopware_Core_KernelTestDebugContainer->getShopware_AppSystem_GuzzleService()

(...)
```

When clearing the cache with --env=test, you get a similar error.

**Comment by johanv** [comment]
Hmm, it seems that this is a duplicate of NEXT-25676. I wasn't aware of the 2nd issue tracker.

**Comment by keulinho** [comment]
I'm closing this as a duplicate you can track the progress in the issue tracker ticket here: https://issues.shopware.com/issues/NEXT-25676
