### ISSUE TITLE
[admin-ui] a page with only a sw-datepicker throws a js error after refreshing the page and the picker does not work

### ISSUE THREAD

**Issue by AubreyHewes** [shopware/platform#3244]
### PHP Version

8.2.3

### Shopware Version

6.5.3.3

### Expected behaviour

A page with only one (or more)  `<sw-datepicker />` components works after refreshing the page (or opening from bookmark etc).

### Actual behaviour

The following errors are thrown for each  `<sw-datepicker/>` instance and the picker does not work. This only occurs when refreshing the page, if you navigate from a page that already had some `<sw-field />` it works. 

<details>
<summary>The error thrown (a few times)</summary>

````
An error was captured in current module: TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at j (d4d0bfe62efeb4ac2177.js:2:56459)
    at new E (d4d0bfe62efeb4ac2177.js:2:57151)
    at a.createFlatpickrInstance (a7357d213557f2534568.js:1:6974)
    at qe (app.js?1690913652:2:565047)
    at a.n (app.js?1690913652:2:566794)
    at qe (app.js?1690913652:2:565047)
    at AdzN.e.$emit (app.js?1690913652:2:588006)
    at An (app.js?1690913652:2:579104)
    at Object.insert (app.js?1690913652:2:574140)
````
</details>

It seems it is not waiting for the ref element before initializing the datepicker's underlying flatpickr instance. 

The weird thing is if you add another arbitrary `<sw-field/>` to the page (order is not important!) it does not throw errors and the pickers work when you refresh the page.

### How to reproduce

1. In a custom module create a new page that only displays one `<sw-datepicker/>` field.
2. Refresh the page.

<details>
<summary>Alternatively use the following code (adds a sub menu to the dashboard)</summary>

````javascript
const { Module, Component } = Shopware;

const title = 'SW Component Library - <sw-datepicker /> render error';

Component.register('sw-component-errors-page', {
  template: '<sw-page><sw-card-view slot="content"><sw-card><router-view /></sw-card></sw-card-view></sw-page>',
});

Component.register('sw-component-errors-sw-datepicker-error', {
  template: `<div>
    <sw-alert>You need to <a @click.prevent="location.reload()">reload</a> the page to see the error in the console</sw-alert>
    <sw-datepicker label="This datepicker does not work"/>
    <router-link to="/sw/component/errors/datepicker/working">See the weird workaround</router-link>
  </div>`,
});

Component.register('sw-component-errors-sw-datepicker-working', {
  template: `<div>
    <sw-alert>You need to <a @click.prevent="location.reload()">reload</a> the page to see the error in the console has been resolved</sw-alert>
    <sw-field label="This arbitrary sw-field component"/>
    <sw-datepicker label="Makes this datepicker work"/>
    <router-link to="/sw/component/errors/datepicker/error">Back to the error</router-link>
  </div>`,
});

Module.register('sw-component-errors', {
  type: 'plugin',
  entity: 'setting',
  name: title,
  title,
  description: title,
  color: '#ff0000',
  icon: 'regular-products',
  favicon: 'icon-module-products.png',
  routes: {
    datepicker: {
      path: 'datepicker',
      component: 'sw-component-errors-page',
      children: {
        error: {
          component: 'sw-component-errors-sw-datepicker-error',
          path: 'error',
        },
        working: {
          component: 'sw-component-errors-sw-datepicker-working',
          path: 'working',
        },
      },
    },
  },
  navigation: [{
    label: 'SW Component Library Errors',
    path: 'sw.component.errors.datepicker.error',
    parent: 'sw-dashboard',
  }],
});
````
</details>

**Comment by AubreyHewes** [comment]
Fixed by https://github.com/shopware/platform/pull/3267
